config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  telegram_webhook TelegramController

  # Defines the root path route ("/")
  root "home#index"

  resources :locations, only: %i[new create edit update] do
    member do
      get :cancel_editing
    end

    resources :products, only: %i[index show new create] do
      member do
        get :edit_name
        get :edit_price
        get :edit_description

        get :cancel_editing_name
        get :cancel_editing_price
        get :cancel_editing_description

        patch :update_name
        patch :update_price
        patch :update_description
      end
    end

    resources :orders
  end
end

app/views/shared/_flash.html.erb
<div
  class="transition transform duration-1000 hidden fixed top-5 left-1/2 -translate-x-1/2 z-50"
  data-controller="notification"
  data-notification-delay-value="5000"
  data-transition-enter-from="opacity-0 translate-y-[-1rem]"
  data-transition-enter-to="opacity-100 translate-y-0"
  data-transition-leave-from="opacity-100 translate-y-0"
  data-transition-leave-to="opacity-0 translate-y-[-1rem]"
>
  <% flash.each do |type, message| %>
    <div class="flex items-center gap-4 <%= type == "notice" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700" %> p-4 rounded-lg shadow-lg max-w-[450px]">
      <p class="text-sm flex-1"><%= message %></p>
      <%= inline_svg_tag "x-mark.svg", class: "cursor-pointer size-6 flex-shrink-0", data: { action: "click->notification#hide"} %>
    </div>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<aside class="w-64 h-screen border-r border-gray-200 bg-gray-50">
  <div class="h-full px-3 py-4">
    <div class="flex justify-center">
      <%= link_to "Добавить локацию", new_location_path, class: "btn blue", data: { turbo_frame: :modal } %>
    </div>

    <ul class="flex flex-col gap-1 mt-8 h-[80vh] overflow-y-auto">
      <% Location.order(:address).each do |location| %>
        <li class="w-fit">
          <turbo-frame id="location-sidebar-<%= location.id %>">
            <%= render "locations/location_sidebar", location: %>
          </turbo-frame>
        </li>
      <% end %>
    </ul>
  </div>
</aside>