config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  telegram_webhook TelegramController

  # Defines the root path route ("/")
  root "home#index"

  resources :locations, only: %i[new create edit update] do
    member do
      get :cancel_editing
    end

    resources :products, only: %i[index show new create] do
      member do
        get :edit_name
        get :edit_price
        get :edit_description

        get :cancel_editing_name
        get :cancel_editing_price
        get :cancel_editing_description

        patch :update_name
        patch :update_price
        patch :update_description
      end
    end

    resources :orders
  end
end

app/models/product.rb
# typed: strict

class Product < ApplicationRecord
  include Discard::Model

  belongs_to :location

  validates :name, presence: true, uniqueness: { scope: :location_id }, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1_000_000 }
  validates :description, length: { maximum: 1000 }, allow_blank: true
end

app/controllers/products_controller.rb
# typed: strict

class ProductsController < ApplicationController
  extend T::Sig

  sig { void }
  def index
    location = Location.includes(:products).find(params[:location_id])
    products = location.products.order(created_at: :desc)

    respond_to do |f|
      f.html { render :index, locals: { location:, products: }, layout: "location" }
    end
  end

  sig { void }
  def new
    location = Location.find(params[:location_id])
    product = Product.new

    respond_to do |f|
      f.html { render :new, locals: { location:, product: } }
    end
  end

  sig { void }
  def show
    location = Location.includes(:products).find(params[:location_id])
    product = location.products.find(params[:id])

    respond_to do |f|
      f.html { render :show, locals: { location:, product: } }
    end
  end

  sig { void }
  def create
    location = Location.find(params[:location_id])
    product = Product.new(location:, **product_params)

    respond_to do |f|
      if product.save
        f.turbo_stream do
          flash.now[:notice] = "Продукт успешно добавлен!"
          render turbo_stream: [
            turbo_stream.append(:flash, partial: "shared/flash"),
            turbo_stream.update(:modal, nil),
            turbo_stream.update(
              :products,
              partial: "products/products",
              locals: { products: location.products.order(created_at: :desc), location: }
            )
          ]
        end
      else
        f.html { render :new, locals: { location:, product: } }
      end
    end
  end

  sig { void }
  def update_name = handle_product_update(:product_name)
  sig { void }
  def update_price = handle_product_update(:product_price)
  sig { void }
  def update_description = handle_product_update(:product_description)

  sig { void }
  def edit_name = handle_edit_form(:product_name)
  sig { void }
  def edit_price = handle_edit_form(:product_price)
  sig { void }
  def edit_description = handle_edit_form(:product_description)

  sig { void }
  def cancel_editing_name = handle_cancel_editing(:product_name)
  sig { void }
  def cancel_editing_price = handle_cancel_editing(:product_price)
  sig { void }
  def cancel_editing_description = handle_cancel_editing(:product_description)

  private

  sig { params(target: Symbol).void }
  def handle_product_update(target)
    location, product = find_location_and_product

    respond_to do |f|
      if product.update(product_params)
        f.turbo_stream do
          flash.now[:notice] = "Успешно обновлено!"
          render turbo_stream: [
            turbo_stream.append(:flash, partial: "shared/flash"),
            turbo_stream.update(target, partial: "products/#{target}", locals: { product:, location: }),
            turbo_stream.update(
              "product_card_#{product.id}", partial: "products/product_card", locals: { product:, location: }
            )
          ]
        end
      else
        f.turbo_stream do
          render turbo_stream: turbo_stream.update(
            target,
            partial: "products/edit_#{target}_form",
            locals: { location:, product: }
          )
        end
      end
    end
  end

  sig { params(target: Symbol).void }
  def handle_edit_form(target)
    location, product = find_location_and_product

    respond_to do |f|
      f.turbo_stream do
        render turbo_stream: turbo_stream.update(
          target,
          partial: "products/edit_#{target}_form",
          locals: { location:, product: }
        )
      end
    end
  end

  sig { params(target: Symbol).void }
  def handle_cancel_editing(target)
    location, product = find_location_and_product

    respond_to do |f|
      f.turbo_stream do
        render turbo_stream: turbo_stream.update(target, partial: "products/#{target}", locals: { product:, location: })
      end
    end
  end

  sig { returns([ Location, Product ]) }
  def find_location_and_product
    location = Location.find(params[:location_id])
    product = location.products.find(params[:id])

    [ location, product ]
  end

  sig { returns(ActionController::Parameters) }
  def product_params = params.require(:product).permit(:name, :description, :price)
end

app/views/products/_edit_product_description_form.html.erb
<%= form_with url: update_description_location_product_path(location, product),
  model: product,
  method: :patch,
  class: "flex gap-2 items-center",
  html: {novalidate: true} do |f|
%>
  <%= render ViewComponents::TextAreaInput.new(
    f, :description,
    placeholder: "Введите описание",
    classes: "w-2/3",
    input_html: { rows: 3 }
  ) %>

  <div class="flex gap-2">
    <%= button_tag type: "submit", class: "btn blue" do %>
      <%= inline_svg_tag "check.svg" %>
    <% end %>

    <%= link_to cancel_editing_description_location_product_path(location, product),
      data: { turbo_frame: :product_description, turbo_stream: true },
      class: "btn gray" do
    %>
      <%= inline_svg_tag "x-mark.svg" %>
    <% end %>
  </div>
<% end %>

app/views/products/_edit_product_name_form.html.erb
<%= form_with url: update_name_location_product_path(location, product),
  model: product,
  method: :patch,
  class: "flex gap-2 items-center",
  html: {novalidate: true} do |f|
%>
  <%= render ViewComponents::TextInput.new(
    f, :name,
    placeholder: "Введите название",
    classes: "w-2/3"
  ) %>

  <div class="flex gap-2">
    <%= button_tag type: "submit", class: "btn blue" do %>
      <%= inline_svg_tag "check.svg" %>
    <% end %>

    <%= link_to cancel_editing_name_location_product_path(location, product),
      data: { turbo_frame: :product_name, turbo_stream: true },
      class: "btn gray" do
    %>
      <%= inline_svg_tag "x-mark.svg" %>
    <% end %>
  </div>
<% end %>

app/views/products/_edit_product_price_form.html.erb
<%= form_with url: update_price_location_product_path(location, product),
  model: product,
  method: :patch,
  class: "flex gap-2 items-center",
  html: {novalidate: true} do |f|
%>
  <%= render ViewComponents::NumberInput.new(
    f, :price,
    placeholder: "Введите цену",
    classes: "w-1/3",
    input_html: { min: 0, step: 0.01 }
  ) %>

  <div class="flex gap-2">
    <%= button_tag type: "submit", class: "btn blue" do %>
      <%= inline_svg_tag "check.svg" %>
    <% end %>

    <%= link_to cancel_editing_price_location_product_path(location, product),
      data: { turbo_frame: :product_price, turbo_stream: true },
      class: "btn gray" do
    %>
      <%= inline_svg_tag "x-mark.svg" %>
    <% end %>
  </div>
<% end %>

app/views/products/_product_card.html.erb
<%= render ViewComponents::ProductCard.new(
  location_id: location.id,
  product_id: product.id,
  product_name: product.name,
  price: product.price,
  description: product.description
) %>

app/views/products/_product_description.html.erb
<div class="flex flex-col">
  <div class="flex gap-2 items-center">
    <p class="text-sm text-gray-500">
      Описание
    </p>

    <%= link_to edit_description_location_product_path(location, product),
      data: { turbo_frame: :product_description, turbo_stream: true },
      title: "Редактировать описание" do
    %>
      <%= inline_svg_tag "pencil-square.svg", class: "text-gray-500" %>
    <% end %>
  </div>

  <p><%= product.description %></p>
</div>

app/views/products/_product_name.html.erb
<div class="flex flex-col">
  <div class="flex gap-2 items-center">
    <p class="text-sm text-gray-500">
      Название
    </p>

    <%= link_to edit_name_location_product_path(location, product),
      data: { turbo_frame: :product_name, turbo_stream: true },
      title: "Редактировать название" do
    %>
      <%= inline_svg_tag "pencil-square.svg", class: "text-gray-500" %>
    <% end %>
  </div>

  <p><%= product.name %></p>
</div>

app/views/products/_product_price.html.erb
<div class="flex flex-col">
  <div class="flex gap-2 items-center">
    <p class="text-sm text-gray-500">
      Цена
    </p>

    <%= link_to edit_price_location_product_path(location, product),
      data: { turbo_frame: :product_price, turbo_stream: true },
      title: "Редактировать цену" do
    %>
      <%= inline_svg_tag "pencil-square.svg", class: "text-gray-500" %>
    <% end %>
  </div>

  <p><%= product.price %></p>
</div>

app/views/products/_products.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 px-4">
  <% products.each do |product| %>
    <turbo-frame id="product_card_<%= product.id %>">
      <%= render "products/product_card", product:, location: %>
    </turbo-frame>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="flex justify-end items-center mb-4 mx-4">
  <%= link_to new_location_product_path(location), class: "flex gap-2 items-center btn blue", data: { turbo_frame: :modal } do %>
    <%= inline_svg_tag "plus-circle.svg" %>
    Добавить продукт
  <% end %>
</div>

<turbo-frame id="products">
  <%= render "products", products:, location: %>
</turbo-frame>

app/views/products/new.html.erb
<%= render ViewComponents::Modal.new(size: ViewComponents::Modal::MEDIUM) do %>
  <%= form_with url: location_products_path(location), model: product, method: :post, html: {novalidate: true} do |f| %>
    <div class="flex gap-2 w-full mb-4">
      <%= render ViewComponents::TextInput.new(
        f, :name,
        label: "Название",
        placeholder: "Введите название",
        classes: "w-1/2"
      ) %>

      <%= render ViewComponents::NumberInput.new(
        f, :price,
        label: "Цена",
        placeholder: "Введите цену",
        classes: "w-1/2",
        input_html: { min: 0, step: 0.01 }
      ) %>
    </div>

    <%= render ViewComponents::TextAreaInput.new(
      f, :description,
      label: "Описание",
      placeholder: "Введите описание",
      classes: "w-full",
      input_html: { rows: 3 }
    ) %>

    <div class="flex justify-center gap-2 mt-4">
      <button type="button" class="btn gray" data-action="click->modal#close">Отмена</button>
      <%= f.submit "Добавить", class: "btn blue" %>
    </div>
  <% end %>
<% end %>

app/views/products/show.html.erb
<%= render ViewComponents::Modal.new(size: ViewComponents::Modal::MEDIUM) do %>
  <div class="flex flex-col gap-6">
    <turbo-frame id="product_name">
      <%= render "products/product_name", product:, location: %>
    </turbo-frame>

    <turbo-frame id="product_price">
      <%= render "products/product_price", product:, location: %>
    </turbo-frame>

    <turbo-frame id="product_description">
      <%= render "products/product_description", product:, location: %>
    </turbo-frame>
  </div>
<% end %>