config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  telegram_webhook TelegramController

  # Defines the root path route ("/")
  root "home#index"

  resources :locations, only: %i[new create edit update] do
    member do
      get :cancel_editing
    end

    resources :products, only: %i[index show new create] do
      member do
        get :edit_name
        get :edit_price
        get :edit_description

        get :cancel_editing_name
        get :cancel_editing_price
        get :cancel_editing_description

        patch :update_name
        patch :update_price
        patch :update_description
      end
    end

    resources :orders
  end
end

app/models/location.rb
# typed: strict

class Location < ApplicationRecord
  include Discard::Model

  T.unsafe(self).after_discard do |location|
    location.products.discard_all
  end

  has_many :products
  has_many :orders

  validates :address,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 255 }
end

app/controllers/locations_controller.rb
# typed: strict

class LocationsController < ApplicationController
  include TurboRedirect
  extend T::Sig

  sig { void }
  def new
    location = Location.new

    respond_to do |f|
      f.html { render :new, locals: { location: } }
    end
  end

  sig { void }
  def create
    location = Location.new(location_params)

    if location.save
      redirect_to location_products_path(location), turbo_frame: "_top", notice: "Location created successfully"
    else
      render :new, locals: { location: }
    end
  end

  sig { void }
  def edit
    location = Location.find(params[:id])

    respond_to do |f|
      f.html { render :edit, locals: { location: } }
    end
  end

  sig { void }
  def cancel_editing
    location = Location.find(params[:id])

    respond_to do |f|
      f.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "location-address",
          partial: "locations/address",
          locals: { location: }
        )
      end
    end
  end

  sig { void }
  def update
    location = Location.find(params[:id])

    respond_to do |f|
      if location.update(location_params)
        flash.now[:notice] = "Адрес успешно обновлен!"

        f.turbo_stream do
          render turbo_stream: [
            turbo_stream.append(:flash, partial: "shared/flash"),
            turbo_stream.update("location-address", partial: "locations/address", locals: { location: }),
            turbo_stream.update(
              "location-sidebar-#{location.id}",
              partial: "locations/location_sidebar",
              locals: { location: }
            )
          ]
        end
      else
        f.html { render :edit, locals: { location: } }
      end
    end
  end

  private

  sig { returns(ActionController::Parameters) }
  def location_params = params.require(:location).permit(:address)
end

app/views/locations/_address.html.erb
<div class="flex items-center gap-2">
  <p class="truncate max-w-[80vw]">
    <%= location.address %>
  </p>

  <%= link_to edit_location_path(location), data: { turbo_frame: "location-address" } do %>
    <%= inline_svg_tag "pencil-square.svg" %>
  <% end %>
</div>

app/views/locations/_edit_form.html.erb
<turbo-frame id="location-address">
  <%= form_with url: location_path(location),
    model: location,
    method: :patch,
    class: "flex gap-2",
    html: {novalidate: true} do |f|
  %>
    <%= render ViewComponents::TextInput.new(
      f, :address,
      placeholder: "Введите адрес",
      classes: "w-1/3"
    ) %>

    <%= f.submit "Обновить", class: "btn blue" %>
    <%= link_to "Отмена", cancel_editing_location_path(location), class: "btn gray", data: { turbo_stream: true } %>
  <% end %>
</turbo-frame>

app/views/locations/_location_sidebar.html.erb
<turbo-frame id="location-sidebar-<%= location.id %>">
  <%= link_to location.address,
    location_products_path(location),
    class: ["p-3 w-fit max-w-48 text-sm block truncate rounded-lg hover:bg-gray-100 hover:font-bold", ("bg-gray-100 font-bold" if request.path.match?(/locations\/#{location.id}(?:\/|$)/))],
    data: { turbo_frame: "_top" },
    title: location.address
  %>
</turbo-frame>

app/views/locations/edit.html.erb
<turbo-frame id="location-address">
  <%= render "locations/edit_form", location: %>
</turbo-frame>

app/views/locations/new.html.erb
<%= render ViewComponents::Modal.new do %>
  <%= form_with url: locations_path, model: location, method: :post, html: {novalidate: true} do |f| %>
    <%= render ViewComponents::TextInput.new(
      f, :address,
      label: "Адрес",
      placeholder: "Введите адрес"
    ) %>

    <div class="flex justify-center gap-2 mt-4">
      <button type="button" class="btn gray" data-action="click->modal#close">Отмена</button>
      <%= f.submit "Создать", class: "btn blue" %>
    </div>
  <% end %>
<% end %>