config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  telegram_webhook TelegramController

  # Defines the root path route ("/")
  root "home#index"

  resources :locations, only: %i[new create edit update] do
    member do
      get :cancel_editing
    end

    resources :products, only: %i[index show new create] do
      member do
        get :edit_name
        get :edit_price
        get :edit_description

        get :cancel_editing_name
        get :cancel_editing_price
        get :cancel_editing_description

        patch :update_name
        patch :update_price
        patch :update_description
      end
    end

    resources :orders
  end
end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Act On" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <turbo-frame id="flash">
      <%= render "shared/flash" %>
    </turbo-frame>
    <turbo-frame id="modal"></turbo-frame>

    <div class="flex">
      <%= render "shared/sidebar" %>

      <main class="flex-1">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<%= render "layouts/application" do %>
  <%= yield %>
<% end %>

app/views/layouts/location.html.erb
<%= render "layouts/application" do %>
  <header class="bg-gray-50 p-4 h-20 flex items-center">
    <turbo-frame id="location-address">
      <%= render "locations/address", location: %>
    </turbo-frame>

  </header>

  <div class="p-4">
    <ul class="flex gap-4 justify-center">
      <li class="bg-gray-50 rounded-lg cursor-pointer border <%= current_page?(location_products_path(location)) ? "border-blue-700" : "hover:bg-gray-100 border-gray-100" %>">
        <%= link_to location_products_path(location), class: "flex p-4 items-center gap-2" do %>
          <%= inline_svg_tag "cube-transparent.svg" %>
          Продукты
        <% end %>
      </li>

      <li class="bg-gray-50 rounded-lg cursor-pointer border <%= current_page?(location_orders_path(location)) ? "border-blue-700" : "hover:bg-gray-100 border-gray-100" %>">
        <%= link_to location_orders_path(location), class: "flex p-4 items-center gap-2" do %>
          <%= inline_svg_tag "document-text.svg" %>
          Заказы
        <% end %>
      </li>
    </ul>
  </div>

  <%= yield %>
<% end %>